/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t wait_millisecond = 1000;
uint32_t wait_counter = 0;

// Define Registers
#define RCC_AHB2ENR *((volatile uint32_t *)0X4002104C)
#define LED1_MODER *((volatile uint32_t *)0x42020800)
#define LED2_MODER *((volatile uint32_t *)0x42020400)
#define PUSHBUTTON_MODER *((volatile uint32_t *)0x42020800)
#define LED1_ODR *((volatile uint32_t *)0x42020814)
#define LED2_ODR *((volatile uint32_t *)0x42020414)
#define PUSHBUTTON_IDR *((volatile uint32_t *)0x42020810)

int main(void)
{
	// Enable Clock for GPIO
	RCC_AHB2ENR |= 1 << 1;
	RCC_AHB2ENR |= 1 << 2;

	// Configure Pin as General purpose output mode
	LED1_MODER &= ~(1 << 15);
	LED2_MODER &= ~(1 << 15);
	PUSHBUTTON_MODER &= ~(1 << 27);
	PUSHBUTTON_MODER &= ~(1 << 26);

	while (1)
	{
		int index;

		if (PUSHBUTTON_IDR & 1 << 13) // PUSH BUTTON BASILIYSA
		{
			// Turn Off BLUE LED
			LED2_ODR &= ~(1 << 7);
			// Turn On GREEN LED
			LED1_ODR |= (1 << 7);
		}
		else
		{
			// Turn Off GREEN LED
			LED1_ODR &= ~(1 << 7);
			// Turn On BLUE LED
			LED2_ODR |= (1 << 7);
		}
	}
}
